		

 
all:	
	C:/Rtools/mingw_64/bin/g++ -std=c++11 -fexceptions -O2 -fexpensive-optimizations -Os -O3 -O2 -O1 -O -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -Wall CONDUCAO.cpp CONVECCAO.cpp DADOS.cpp EnxameParticulas.cpp main.cpp PROPRIEDADES.cpp Random.cpp  RESFRIAMENTO.cpp -Wl,--export-dynamic -fopenmp -o ResfPSO

